### ISSUE TITLE
Exception on Refresh

### ISSUE THREAD

**Issue by bradobro** [kcyarn/markdown-document#15]
Do you have any idea, @kcyarn, where in the code I might debug this? I'd be interested in making a PR.

# Atom Exception Report

## Steps leading up to the error:

1. Load a long Markdown document (ApiBlueprint).
2. Use the command palette to run `Markdown Document: Toggle`. No sidebar appears.
3. Use the command palette to run `Markdown Document: Refreh`.  This exception occurs...

**Atom Version**: 1.13.0
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [markdown-document](https://github.com/kcyarn/markdown-document) package, v0.2.1

### Stack Trace

Uncaught TypeError: this.refreshClick is not a function

```
At /Users/brad/.atom/packages/markdown-document/lib/markdown-document-view.coffee:324

TypeError: this.refreshClick is not a function
    at MarkdownDocumentView.module.exports.MarkdownDocumentView.refreshOutline (/Users/brad/.atom/packages/markdown-document/lib/markdown-document-view.coffee:324:6)
    at Object.refresh (/Users/brad/.atom/packages/markdown-document/lib/markdown-document.coffee:47:27)
    at atom-workspace.subscriptions.add.atom.commands.add.markdown-document:refresh (/Users/brad/.atom/packages/markdown-document/lib/markdown-document.coffee:30:93)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -9:46.3.0 find-and-replace:focus-next (input.hidden-input)
  8x -9:45.3.0 core:backspace (input.hidden-input)
     -9:37.7.0 core:save (input.hidden-input)
     -0:40.3.0 markdown-document:toggle (input.hidden-input)
     -0:33.2.0 command-palette:toggle (input.hidden-input)
  3x -0:27.8.0 core:move-down (input.hidden-input)
     -0:23.3.0 core:confirm (input.hidden-input)
     -0:23.3.0 markdown-document:toggle (input.hidden-input)
     -0:13.7.0 editor:consolidate-selections (input.hidden-input)
     -0:13.7.0 core:cancel (input.hidden-input)
     -0:08.7.0 command-palette:toggle (input.hidden-input)
  4x -0:02.6.0 core:move-down (input.hidden-input)
     -0:00.1.0 core:confirm (input.hidden-input)
     -0:00.1.0 markdown-document:refresh (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "go-find-references",
      "go-signature-statusbar",
      "godef",
      "markdown-table-formatter"
    ],
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.16 (active)
git-plus, v7.1.0 (active)
go-debug, v1.0.3 (active)
go-find-references, v1.2.3 (inactive)
go-outline, v0.6.2 (inactive)
go-plus, v5.1.0 (active)
go-rename, v0.3.0 (active)
go-signature-statusbar, v1.2.0 (inactive)
godef, v0.2.5 (inactive)
hyperclick, v0.0.39 (active)
linter, v1.11.21 (active)
linter-golint, v0.3.0 (active)
linter-golinter, v1.2.1 (active)
markdown-document, v0.2.1 (active)
markdown-table-formatter, v2.8.4 (inactive)
markdown-toc, v0.4.2 (inactive)
markdown-writer, v2.6.3 (active)
project-plus, v0.9.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (active)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (active)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by kcyarn** [comment]
You want the master branch, file lib/markdown-document-view.coffee,
which contains everything. I didn't break it into modules and really
don't plan to at this time. I don't normally break things out unless I
exceed 500 lines. If not having everything grouped within the same
file makes you feel more comfortable, feel free to change it.

Markdown-document currently uses a panel to display the outline. In
the past, this did not interfere with the spellcheck. As of Atom
1.12.7, it does. I don't know if this is a conflict with atom itself
or the spellcheck package. Without checking the change logs for Atom
1.13, I don't know if this problem got worse, but I assume it did.

The outline is Angular 1 because that was the quickest way to
implement the auto refresh that didn't conflict with atom. I
restructured the code for 0.2.1, but didn't rewrite it. I just moved
things around until it played nicely with atom's latest version of
coffee script. I don't think I tested the refreshclick function. I
never use it and actually forgot it existed until I read this this
morning so uh...yeah...oops. Off the top of my head, I think I made it
part of the angular component for some bizarre reason. If I did, then
@refreshClick() is looking for a function that is now contained within
the angular 1 controller.

I currently run Atom 1.12.7. I typically run several updates behind
the latest version because every time I update Atom multiple crucial
to my workflow packages break. I'm skipping the 1.13 update. I just
can't justify the time needed to change my terminal package again.
Sorry. I know that's not helpful for troubleshooting.

Sent from My Phone.

I'll check the code tonight on a larger screen and verify this is what I did.

**Comment by bradobro** [comment]
Thanks @kcyarn. I like the idea of going somewhere Scrivener-like with this. (I like Scrivener, but miss the editing power of Atom or Sublime when I use it. Seems to me there was a little unnecessary finickiness about Markdown too.)

**Comment by kcyarn** [comment]
I have sketches, the beginnings of an angular 2 electron/cordova app
because I desperately need the ability to edit the same project on my
tablet and phone as on my PC, using a similar interface, and with the
option of at least reading my notes without having to open a separate file
or scroll up/down in the current file. I almost hate myself for thinking I
should just go with medium.js (html barebones wysiwyg that plays nicely
with android chrome) and either convert it to markdown to save into
individual files or just save those files as html. I'm leaning toward
markdown because of diff. Oh, and outside of compiling (everything I do
ends up as latex to pdf for print or epub/mobi) I need version control
(git) with the provider of my choice. I haven't pushed this anywhere yet
and I only get to work on it in thirty minute spurts, but I completely get
what you're saying.

My biggest issue with scrivener is and always has been its rtf files and
how it compiles those files into epubs that don't validate, mobis that
freeze up, and html that looks almost as bad as what I'd get out of word.
The quasi-markdown approach they suggest for markdown use is almost as bad.

I actually hate writing in markdown, but I like using the asterisks as
shortcuts.

I originally saw myself doing all this through an atom package with a
separate cordova interface using the same files, but not anymore. At least
with electron, I can fix the version number and should that ever fail
swapping over to nwjs isn't a deal breaker.

**Comment by olafklingt** [comment]
I have the same problem. as the original poster.

**Comment by kcyarn** [comment]
After reviewing the alternatives, I've deprecated this in favor of [document-outline](https://atom.io/packages/document-outline), which seems to accomplish the same thing. Sorry for the wait.
